= gestion des départs

== Signature

Une seule fonction regroupe actuellement l'ensemble des traitements permettant

- Le calcul des populations destinés à partir
- La construction des agents avions `MobileGroup`


.Arguments de la fonction
[options="header"]
|===
| argument de la fonction |signification
| #cumulated-pop-flight-expected-float| population cumulée
| #instantaneous-total-population-to-fly | population autorisé à voler 
| #airplane-size | taille de l'avion 
| #strategy-redistribution | booléen pour indiquer si il y a redistribution ou pas des populations en cas de non départ
|===

Les populations (`#cumulated-pop-flight-expected-float` et `#instantaneous-total-population-to-fly`) qui sont passés en paramètres de cette fonction sont mis à jour à chaque nouvelle itération du modèle (`ticks`). Le calcul de ces populations est décrit sur la page décrivant la link:./procedure-principale.adoc[procédure principale].

== Calcul des autorisations

Première partie, on calcule au niveau des noeud la population qui va être autorisé à voler.

[source,bash]
----
    ask nodes  
    [ 
      let my-instantaneous-total-population-to-fly #instantaneous-total-population-to-fly / number-nodes
      set stock-to-flight stock-to-flight + my-instantaneous-total-population-to-fly
      set #cumulated-pop-flight-expected-float #cumulated-pop-flight-expected-float + my-instantaneous-total-population-to-fly
    ]
    
    ask nodes  
    [
      set stock-to-flight stock-to-flight
    ]
----

