= gestion des départs

== Signature

Une seule fonction regroupe actuellement l'ensemble des traitements permettant

- Le calcul des populations destinés à partir
- La construction des agents avions `MobileGroup`


.Arguments de la fonction
[options="header"]
|===
| argument de la fonction |signification
| #cumulated-pop-flight-expected-float| population cumulée
| #instantaneous-total-population-to-fly | stock de population susceptible de partir, cumulé sur l'ensemble des noeuds.
| #airplane-size | taille de l'avion 
| #strategy-redistribution | booléen pour indiquer si il y a redistribution ou pas des populations en cas de non départ
|===

Les populations (`#cumulated-pop-flight-expected-float` et `#instantaneous-total-population-to-fly`) qui sont passés en paramètres de cette fonction sont mis à jour à chaque nouvelle itération du modèle (`ticks`). Le calcul de ces populations est décrit sur la page décrivant la link:./procedure-principale.adoc[procédure principale].

== Mise à jour de la population

Première partie, on calcule au niveau des noeud la population qui va être autorisé à voler.


[source,bash]
----
    ask nodes  
    [ 
      let my-instantaneous-total-population-to-fly #instantaneous-total-population-to-fly / number-nodes //<1>
      set stock-to-flight stock-to-flight + my-instantaneous-total-population-to-fly // <2>
    ]

----

<1> On rapporte cette population à chaque noeud. En réalité, `#instantaneous-total-population-to-fly` est une constante qui n'a pas de raison de varier, car celle-ci découle du calibrage. On notera ici que l'on passe d'un entier à un flottant au niveau de la population.

<2> On la stocke au niveau de chaque aéroport, car cette population se cumule.

On assume ici le fait que la populaiton sur le noeuf est toujours plus grande que la population amené à voyager, ce qui explique l'absence de code testant cette hypothèse.
