= procedure-principale.adoc

== Mise à jour des aéroports 

[source,bash]
----
ask nodes[
    update-node-airport self
  ]
----

La mise à jour des aéroports est variable selon les différentes stratégies, la procédure qui se charge de modifier les états d'entrées et des sorties de chacun des aéroports est ainsi décrite plus en détail dans la page link:./gestionentreessorties_aeroports.adoc[gestion des entrées sorties des aéroports].

== Calcul des différentes populations 

L'appel de la fonction qui construit les avions (`update-world`), décrite sur la page link:./gestion_des_departs.adoc[gestion des départs] renvoie deux populations, stockées dans des globales :

`gsum-pop-flight-real`:: 
Population effectivement partie des aéroports, c'est à dire contenu dans les avions.

`gsum-pop-flight-expected` :: 
Population qui aurait du partir des aéroports. En effet, du fait des différentes stratégies, il existe pour chaque nouvel avion prêt à partir, un différentiel entre la population destiné à monter dans un avion, et la population qui est effectivement monté dans l'avion.

A partir de ces populations calculées à chaque itération, on construit deux globales cumulant ces valeurs sur plusieurs itérations : 

- `gcumulated-pop-flight-real`
- `gcumulated-pop-flight-expected`

La variable indiquant la réduction de traffic subit à chaque itération (`gout-traffic-reduction-instantaneous`) est calculé en faisant le différentiel entre ces deux variables :

[source,bash]
----
set gout-traffic-reduction-instantaneous (gsum-pop-flight-expected - gsum-pop-flight-real) / (max list gsum-pop-flight-expected 1)`
----

On fera attention donc dans ce calcul à une possible division par zéro, ce qui explique le code `(max list gsum-pop-flight-expected 1)`

Afin de garder en mémoire quel a été la réduction maximale de traffic en fin de simulation, on garde une trace de celle-ci grâce à la variable globale `gtaux-reduc-max` :

[source,bash]
----
    if (gtaux-reduc-max < gout-traffic-reduction-instantaneous) 
    [
      set gtaux-reduc-max gout-traffic-reduction-instantaneous
    ]
----
